name: jnu_bus_routes
description: "JnU Bus Routes - Complete rewrite with proper version compatibility"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Icons
  cupertino_icons: ^1.0.8
  shadcn_ui: ^0.38.1
  google_fonts: ^6.2.1
  
  # Navigation
  go_router: ^16.2.5
  
  # State Management - Riverpod 2.x
  flutter_riverpod: ^2.5.3
  riverpod: ^2.5.3
  riverpod_annotation: ^2.3.5
  
  # Local Storage
  shared_preferences: ^2.3.3
  sqflite: ^2.3.3+2
  path_provider: ^2.1.4
  path: ^1.9.0
  
  # Utils
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.13
  custom_lint: ^0.7.6
  riverpod_lint: ^2.3.13

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/database/jnu.db

  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
